spring:
  application:
    name: northwind
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/northwind}
    username: ${DATABASE_USERNAME:northwind}
    password: ${DATABASE_PASSWORD:northwind}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080
  forward-headers-strategy: framework

logging:
  level:
    org.hibernate.SQL: warn
    org.springframework.security: info
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
