spring:
  application:
    name: northwind-test
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true

server:
  port: 0

logging:
  level:
    org.hibernate.SQL: warn
    org.springframework.security: warn
    org.testcontainers: warn

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
