name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test and Validate
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Validate Maven configuration
      run: |
        cd northwind
        mvn validate

    - name: Compile source code
      run: |
        cd northwind
        mvn compile -q

    - name: Run unit tests
      run: |
        cd northwind
        mvn test -Dtest="!*IntegrationTest" -q
      env:
        SPRING_PROFILES_ACTIVE: test

    - name: Run integration tests
      run: |
        cd northwind
        mvn test -Dtest="*IntegrationTest" -q
      env:
        SPRING_PROFILES_ACTIVE: test

    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Maven Tests
        path: northwind/target/surefire-reports/*.xml
        reporter: java-junit

    - name: Build application
      run: |
        cd northwind
        mvn package -DskipTests -q

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: northwind/target/surefire-reports/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: build-artifacts
        path: northwind/target/*.jar

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        cd northwind
        docker build -t northwind-api:${{ github.sha }} .
        docker build -t northwind-api:latest .

    - name: Test Docker image
      run: |
        cd northwind
        docker run --rm -d --name test-container -p 8080:8080 northwind-api:${{ github.sha }}
        sleep 30
        curl -f http://localhost:8080/actuator/health || exit 1
        docker stop test-container
