name: PR Validation

on:
  pull_request:
    branches: [ main, master ]

jobs:
  quick-validation:
    name: Quick Validation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Validate Maven configuration
      run: |
        cd northwind
        mvn validate

    - name: Compile source code
      run: |
        cd northwind
        mvn compile -q

    - name: Run unit tests only
      run: |
        cd northwind
        mvn test -Dtest="!*IntegrationTest" -q
      env:
        SPRING_PROFILES_ACTIVE: test

    - name: Build application
      run: |
        cd northwind
        mvn package -DskipTests -q
